version: '3.8'

services:
  APPLICATION_NAME-dev:
    container_name: APPLICATION_NAME-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: unless-stopped
    ports:
      - 3000:3000
    command: yarn start
    volumes:
      - ./:/app
